# Simple GoReleaser config untuk sfDBTools_new
project_name: sfDBTools

before:
  hooks:
    - go mod tidy

builds:
  - id: sfDBTools
    main: ./main.go
    binary: sfDBTools
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X sfDBTools/internal/version.Version={{.Version}}
      - -X sfDBTools/internal/version.Commit={{.Commit}}
      - -X sfDBTools/internal/version.Date={{.Date}}

archives:
  - id: archives
    builds:
      - sfDBTools
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md
      - SETUP_SUMMARY.md
      - "config/config.yaml"
      - "config/config.example.yaml"
      - "config/key_maria_nbc.txt"
      - "config/server.cnf"
      - "config/db_config/**"
      - "config/db_list/**"

checksum:
  name_template: "checksums_{{ .Version }}.txt"

signs:
  # Aktifkan kalau kamu pakai cosign / minisign
  # - artifacts: checksum
  #   cmd: cosign
  #   args: ["sign-blob", "--output-signature", "${signature}", "${artifact}"]
  #   signature: "${artifact}.sig"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  prerelease: false