---
- name: Clean Install and Configure MariaDB
  hosts: all
  become: yes
  vars:
    mariadb_src_key_file: /root/dba/key.txt
    mariadb_repo_file: /etc/yum.repos.d/MariaDB.repo
    mariadb_service_override: /etc/systemd/system/mariadb.service.d/override.conf
    mariadb_config_file: /var/lib/mariadb/server.cnf
    mariadb_data_dir: /var/lib/mariadb/data
    mariadb_log_dir: /var/lib/mariadb/log
    mariadb_binlog_dir: /var/lib/mariadb/binlog
    mariadb_key_file: /var/lib/mariadb/data/key.txt

  tasks:
    - name: Check if MariaDB service exists
      ansible.builtin.command:
        cmd: systemctl status mariadb
      ignore_errors: true
      register: mariadb_service_status

    - name: Ensure MariaDB is stopped if service exists
      ansible.builtin.systemd:
        name: mariadb
        state: stopped
        enabled: no
      when: mariadb_service_status.rc == 0

    - name: Remove existing MariaDB installation
      ansible.builtin.yum:
        name:
          - MariaDB-server
          - MariaDB-client
          - MariaDB-shared
          - MariaDB-common
          - rsync
        state: absent

    - name: Remove old MariaDB configurations and directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/my.cnf
        - /etc/my.cnf.d
        - /etc/mariadb*
        - /var/lib/mysql
        - /var/log/mariadb

    - name: Add MariaDB repository
      ansible.builtin.copy:
        dest: "{{ mariadb_repo_file }}"
        content: |
          # MariaDB 10.6 CentOS repository list - created 2024-10-10 12:00 UTC
          [mariadb]
          name = MariaDB
          baseurl = https://mirror.mariadb.org/yum/10.6/centos/9/x86_64/
          gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
          gpgcheck=1

    - name: Install MariaDB and dependencies
      ansible.builtin.yum:
        name:
          - MariaDB-server
          - MariaDB-client
          - MariaDB-shared
          - MariaDB-common
          - rsync
        state: present
        update_cache: yes

    - name: Modify ProtectHome to false in mariadb.service
      ansible.builtin.lineinfile:
        path: /usr/lib/systemd/system/mariadb.service
        regexp: '^ProtectHome=true'
        line: 'ProtectHome=false'
        backup: yes  # Backup the original file before editing
      notify: Reload systemd daemon

    - name: Create necessary directories for MariaDB
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'
      with_items:
        - "{{ mariadb_data_dir }}"
        - "{{ mariadb_log_dir }}"
        - "{{ mariadb_binlog_dir }}"

    - name: Sync existing MariaDB data directory to new location
      ansible.builtin.command:
        cmd: "rsync -av /var/lib/mysql/ {{ mariadb_data_dir }}/"
      register: rsync_output
      ignore_errors: yes

    - name: Change ownership of MariaDB directories
      ansible.builtin.command:
        cmd: "chown -R mysql:mysql {{ item }}"
      with_items:
        - "{{ mariadb_data_dir }}"
        - "{{ mariadb_log_dir }}"
        - "{{ mariadb_binlog_dir }}"
      ignore_errors: yes

    - name: Copy default MariaDB configuration file
      ansible.builtin.copy:
        src: /etc/my.cnf
        dest: "{{ mariadb_config_file }}"
        remote_src: yes
        force: yes

    - name: Create systemd override directory for MariaDB
      ansible.builtin.file:
        path: /etc/systemd/system/mariadb.service.d
        state: directory

    - name: Add override configuration for MariaDB service
      ansible.builtin.copy:
        dest: "{{ mariadb_service_override }}"
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/sbin/mysqld --defaults-file={{ mariadb_config_file }}

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start MariaDB service
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Add firewall rules
      ansible.builtin.command:
        cmd: "firewall-cmd --zone=public --add-port={{ item }}/tcp --permanent"
      with_items:
        - 3306
        - 10050
      notify: Reload firewall

    - name: Reload firewall
      ansible.builtin.command:
        cmd: "firewall-cmd --reload"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Copy encryption key file to MariaDB data directory
      ansible.builtin.copy:
        src: "{{ mariadb_src_key_file }}"
        dest: "{{ mariadb_key_file }}"
        owner: mysql
        group: mysql
        mode: '0600'

    - name: Update MariaDB server configuration with additional settings
      ansible.builtin.copy:
        dest: "{{ mariadb_config_file }}"
        content: |
          [server]
          log_warnings                                    = 1
          server_id                                       = 603
          gtid-domain-id                                  = 1
          gtid_ignore_duplicates                          = ON
          gtid_strict_mode                                = 1
          rpl_semi_sync_master_enabled                    = ON
          rpl_semi_sync_slave_enabled                     = ON
          rpl_semi_sync_master_wait_point                 = AFTER_SYNC
          slave-skip-errors                               = 1062,1032
          
          [mysqld]
          thread_handling                                 = pool-of-threads
          plugin-load-add                                 = file_key_management
          file_key_management_encryption_algorithm        = AES_CTR
          file_key_management_filename                    = {{ mariadb_key_file }}
          innodb-encrypt-tables
          log_bin                                         = {{ mariadb_binlog_dir }}/mysql-bin
          datadir                                         = {{ mariadb_data_dir }}
          lower_case_table_names                          = 1
          sql-mode                                        = "PIPES_AS_CONCAT"
          skip-host-cache
          skip-name-resolve
          log-slave-updates                               = 1
          query_cache_size                                = 0 #query cache is not supported with wsrep
          query_cache_type                                = 0 #query cache is not supported with wsrep

          # LIMIT #
          net_buffer_length                               = 16384
          max_allowed_packet                              = 1G
          expire_logs_days                                = 3
          max_connections                                 = 10000
          max_connect_errors                              = 1000
          wait_timeout                                    = 40
          interactive_timeout                             = 40
          max_statement_time                              = 900
          open-files-limit                                = 393210

          # INNODB #
          default_storage_engine                          = InnoDB
          innodb_data_home_dir                            = {{ mariadb_data_dir }}
          innodb_log_group_home_dir                       = {{ mariadb_data_dir }}
          innodb_file_per_table                           = 1
          innodb_log_file_size                            = 2G
          innodb_autoinc_lock_mode                        = 2
          innodb_flush_log_at_trx_commit                  = 0
          innodb_doublewrite                              = 1
          binlog_format                                   = ROW
          log_bin_trust_function_creators                 = 1

          log_error                                       = {{ mariadb_log_dir }}/mysql_error.log
          slow_query_log                                  = 1
          slow_query_log_file                             = {{ mariadb_log_dir }}/mysql_error.log

          port                                            = 3306 #custom - EDIT TERLEBIH DAHULU
          bind-address                                    = 0.0.0.0

          performance_schema                              = ON
          
          innodb_buffer_pool_size                         = 4G
          innodb_buffer_pool_instances                    = 4
          innodb_buffer_pool_chunk_size                   = 128M
          thread_cache_size                               = 256
          join_buffer_size                                = 1M
          key_buffer_size                                 = 128M
          max_heap_table_size                             = 512M
          tmp_table_size                                  = 512M
          table_open_cache                                = 2000
          table_definition_cache                          = 400
          innodb_flush_method                             = O_DIRECT
        owner: mysql
        group: mysql
        mode: '0644'

    - name: Restart MariaDB to apply new configurations
      ansible.builtin.systemd:
        name: mariadb
        state: restarted

  handlers:
    - name: Reload firewall
      ansible.builtin.command:
        cmd: "firewall-cmd --reload"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes