name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          
      - name: Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Verify GoReleaser config
        run: |
          if [ ! -f .goreleaser.yaml ]; then
            echo "Error: .goreleaser.yaml not found"
            exit 1
          fi
          echo "GoReleaser config found: .goreleaser.yaml"
          
          # Verify required config files exist
          if [ ! -f config/config.yaml ]; then
            echo "Warning: config/config.yaml not found - will not be included in release"
          else
            echo "Config file found: config/config.yaml"
          fi
          
          if [ ! -f config/config.example.yaml ]; then
            echo "Warning: config/config.example.yaml not found"
          else
            echo "Example config found: config/config.example.yaml"
          fi
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
